import type { SiteBrand } from "../../lib/site-brand";
import { DEFAULT_THEME_PACK_TOKENS } from "../../lib/site-stack";

export const threatIntelligenceBrand: SiteBrand = {
  id: "threat-intelligence",
  appTitle: "Threat Intelligence",
  appDescription: "ANTHUS THREAT INTELLIGENCE from Anthus AI Solutions.",
  mastheadTitle: "THREAT INTELLIGENCE",
  mastheadSubtitle: "from Anthus AI Solutions",
  mastheadTagline: "Practical advice for staying secure as the threat landscape shifts.",
  backToHomeLabel: "Back to Threat Intelligence",
  articleTitleSuffix: "Threat Intelligence",
  placeholderByline: "Anthus AI Solutions",
  defaultPresentation: "blog",
  forcedPresentation: "blog",
  textFont: 'system-ui, -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  footerTitle: "ANTHUS THREAT INTELLIGENCE",
  footerSubtitleOverride: "",
  mastheadWordSplit: true,
  mastheadDateFormat: "formatted",
  mastheadSource: "brand",
  sectionLinkStrategy: "anchor",
  defaultVideoCredit: "Anthus Threat Intelligence video",
  themePack: "threat-intelligence",
  themeTokens: {
    ...DEFAULT_THEME_PACK_TOKENS,
    paper: "#f5f0e6",
    moss: "#1c1917",
    ochre: "#ea580c",
    ink: "#44403c",
  },
  renderer: { kind: "pretext" },
  hosting: { kind: "amplify-ssr" },
  opsChrome: "app",
};
