import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * `papyrus-app sync`: write one-line route shims for Papyrus's routes into the
 * publication repo (SPIKE, PPY-82be6c). Output is generated and gitignored;
 * a site-owned file at the same path (no GENERATED header) always wins.
 */
const MARKER = "// GENERATED by `papyrus-app sync` from @anthusai/papyrus. Do not edit; add a site-owned file at this path to override.";
const NEXT_EXPORTS = new Set([
  "generateMetadata", "metadata", "generateStaticParams", "generateViewport", "viewport",
  "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS",
]);
const GITIGNORE_BEGIN = "# >>> papyrus-app sync (generated route shims)";
const GITIGNORE_END = "# <<< papyrus-app sync";

const pkgRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PKG = "@anthusai/papyrus";

function isGenerated(file) {
  try {
    return fs.readFileSync(file, "utf8").startsWith(MARKER);
  } catch {
    return false;
  }
}

function shimFor(route) {
  const spec = `${PKG}/${route.file.replace(/\.(tsx|ts)$/, "")}`;
  const lines = [MARKER];
  const named = route.exports.filter((n) => NEXT_EXPORTS.has(n));
  if (route.hasDefault) lines.push(`export { default${named.length ? ", " + named.join(", ") : ""} } from "${spec}";`);
  else if (named.length) lines.push(`export { ${named.join(", ")} } from "${spec}";`);
  // Route-segment config must be a literal in the route file itself.
  for (const [name, literal] of Object.entries(route.config)) lines.push(`export const ${name} = ${literal};`);
  return lines.join("\n") + "\n";
}

function middlewareShim(manifest) {
  const matcher = manifest.middleware.matcher ?? '["/((?!_next/static|_next/image|favicon.ico|icon).*)"]';
  return [
    MARKER,
    `export { middleware } from "${PKG}/middleware";`,
    `export const config = { matcher: ${matcher} };`,
    "",
  ].join("\n");
}

const RESERVED_FIRST_SEGMENTS = new Set(["newsroom", "api", "_next", "_preview", "%5F_preview"]);

export function normalizeReaderBasePath(value) {
  const trimmed = (value ?? "").trim().replace(/\/+$/, "");
  if (!trimmed) return "";
  return trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
}

export function readReaderBasePath(root) {
  let text;
  try {
    text = fs.readFileSync(path.join(root, "papyrus.config.ts"), "utf8");
  } catch {
    return "";
  }
  const match = text.match(/\breaderBasePath\s*:\s*(["'`])([^"'`]*)\1/);
  return normalizeReaderBasePath(match ? match[2] : "");
}

export function sync({ root = process.cwd(), log = console.log, manifest: manifestOverride, readerBasePath: readerBasePathOverride } = {}) {
  const manifest = manifestOverride ?? JSON.parse(fs.readFileSync(path.join(pkgRoot, "routes.manifest.json"), "utf8"));
  const readerBasePath = normalizeReaderBasePath(readerBasePathOverride ?? readReaderBasePath(root));
  if (readerBasePath && RESERVED_FIRST_SEGMENTS.has(readerBasePath.split("/")[1])) {
    throw new Error(`readerBasePath "${readerBasePath}" collides with a Papyrus-owned route (newsroom, api, _preview)`);
  }
  const readerRouteFile = (file) => (readerBasePath ? file.replace(/^app\//, `app${readerBasePath}/`) : file);
  const generated = [];
  const skipped = [];
  const write = (relPath, content) => {
    const dest = path.join(root, relPath);
    if (fs.existsSync(dest) && !isGenerated(dest)) {
      skipped.push(relPath);
      return;
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content);
    generated.push(relPath);
  };
  for (const route of manifest.routes) write(route.reader ? readerRouteFile(route.file) : route.file, shimFor(route));
  write("middleware.ts", middlewareShim(manifest));

  // Remove shims that are no longer in the manifest (e.g. after an upgrade).
  const stateFile = path.join(root, ".papyrus", "generated.json");
  let previous = [];
  try { previous = JSON.parse(fs.readFileSync(stateFile, "utf8")); } catch { /* first run */ }
  for (const rel of previous) {
    if (!generated.includes(rel) && isGenerated(path.join(root, rel))) fs.rmSync(path.join(root, rel));
  }
  fs.mkdirSync(path.dirname(stateFile), { recursive: true });
  fs.writeFileSync(stateFile, JSON.stringify(generated, null, 2) + "\n");

  // Keep generated shims out of git.
  const giFile = path.join(root, ".gitignore");
  const gi = fs.existsSync(giFile) ? fs.readFileSync(giFile, "utf8") : "";
  const block = [GITIGNORE_BEGIN, ...generated.map((g) => "/" + g), "/.papyrus/", GITIGNORE_END].join("\n");
  const re = new RegExp(`${GITIGNORE_BEGIN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${GITIGNORE_END}`);
  fs.writeFileSync(giFile, re.test(gi) ? gi.replace(re, block) : `${gi}${gi.endsWith("\n") || !gi ? "" : "\n"}${block}\n`);

  log(`papyrus-app sync: ${generated.length} shim(s) written, ${skipped.length} site-owned file(s) kept (${PKG}@${manifest.version})${readerBasePath ? `, reader mounted at ${readerBasePath}` : ""}`);
  for (const rel of skipped) log(`  site-owned: ${rel}`);
  return { generated, skipped };
}
